-- Modulo Notas para ZaPOS.
-- Ejecutar en Supabase SQL Editor.
-- La app actual usa Supabase Auth para entrar, pero sus datos operativos son compartidos
-- y los servicios existentes no filtran por usuario. Por eso no se habilita RLS por usuario aqui.

create table if not exists public.notas (
  id bigint generated by default as identity primary key,
  titulo varchar(150) not null,
  descripcion text,
  prioridad varchar(20) not null default 'normal',
  estado varchar(20) not null default 'pendiente',
  fijada boolean not null default false,
  fecha_nota timestamptz,
  tipo_relacion varchar(30),
  id_relacion bigint,
  usuario_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint notas_prioridad_check
    check (prioridad in ('normal', 'importante', 'urgente')),

  constraint notas_estado_check
    check (estado in ('pendiente', 'completada')),

  constraint notas_tipo_relacion_check
    check (
      tipo_relacion is null
      or tipo_relacion in ('cliente', 'deuda', 'producto', 'venta', 'caja')
    )
);

create index if not exists idx_notas_estado on public.notas (estado);
create index if not exists idx_notas_prioridad on public.notas (prioridad);
create index if not exists idx_notas_fecha on public.notas (fecha_nota);
create index if not exists idx_notas_fijada on public.notas (fijada);
create index if not exists idx_notas_usuario on public.notas (usuario_id);
create index if not exists idx_notas_relacion on public.notas (tipo_relacion, id_relacion);

create or replace function public.set_notas_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_notas_updated_at on public.notas;
create trigger trg_notas_updated_at
before update on public.notas
for each row
execute function public.set_notas_updated_at();

grant select, insert, update, delete on public.notas to authenticated;
grant usage, select on sequence public.notas_id_seq to authenticated;
